name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  NAME: ""
  VERSION: ""
  NEW_VERSION: ""

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Set Environment Variables
        run: |
          export NAME=$(mvn help:evaluate -Dexpression=project.name | grep "^[^\[]")
          export VERSION=$(mvn help:evaluate -Dexpression=project.version | grep "^[^\[]")
          echo "NAME: $NAME"
          echo "VERSION: $VERSION"
          echo "##[set-output name=NAME;]$NAME"
          echo "##[set-output name=VERSION;]$VERSION"
          id: set-env

      - name: Increase Patch version
        run: |
          # Parse the version components
          MAJOR=$(echo ${{ steps.set-env.outputs.VERSION }} | cut -d. -f1)
          MINOR=$(echo ${{ steps.set-env.outputs.VERSION }} | cut -d. -f2)
          PATCH=$(echo ${{ steps.set-env.outputs.VERSION }} | cut -d. -f3)

          # Increment the Patch version
          PATCH=$((PATCH + 1))

          # Create the new version
          NEW_VERSION="$MAJOR.$MINOR.$PATCH"
          echo "##[set-output name=NEW_VERSION;]$NEW_VERSION"

          # Use Maven to set the new version using versions-maven-plugin
          mvn versions:set -DnewVersion=$NEW_VERSION

          # Print the new version
          echo "New version: $NEW_VERSION"

      - name: Build Docker image
        run: |
          docker build --build-arg NAME=${{ steps.set-env.outputs.NAME }} --build-arg NEW_VERSION=${{ steps.set-env.outputs.NEW_VERSION }} -t ${{ steps.set-env.outputs.NAME }} .

