name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  NAME: ""
  VERSION: ""

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Get Maven Project Name and Version
        run: |
          export NAME=$(mvn help:evaluate -Dexpression=project.name | grep "^[^\[]")
          export VERSION=$(mvn help:evaluate -Dexpression=project.version | grep "^[^\[]")

      - name: Debug Maven Properties
        run: |
          echo "NAME: $NAME"
          echo "VERSION: $VERSION"

      - name: Increase Patch version
        run: |
          # Parse the version components
          MAJOR=$(echo $VERSION | cut -d. -f1)
          MINOR=$(echo $VERSION | cut -d. -f2)
          PATCH=$(echo $VERSION | cut -d. -f3)

          # Increment the Patch version
          PATCH=$((PATCH + 1))

          # Create the new version
          NEW_VERSION="$MAJOR.$MINOR.$PATCH"

          # Use Maven to set the new version
          mvn build-helper:parse-version versions:set "-DnewVersion=${NEW_VERSION}"

          # Print the new version
          echo "New version: $VERSION"

      - name: Build Docker image
        run: |
          docker build -t $NAME .


